# Generated by Django 2.1.1 on 2018-09-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=16),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['store', 'removed', 'created_at'], name='kiorder_tic_store_i_132ade_idx'),
        ),
    ]
