# Generated by Django 2.1.2 on 2018-11-11 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiorder', '0002_auto_20180929_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_active_users', to='kiorder.Store'),
        ),
        migrations.AddField(
            model_name='user',
            name='kiosk_franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_franchise_users', to='kiorder.Franchise'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_stores',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='users_preferring_this', to='kiorder.Store'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('kiosk', 'kiosk'), ('customer', 'customer')], default='customer', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='kiorder.Tx'),
        ),
        migrations.AlterField(
            model_name='tx',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='txlog',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
