# Generated by Django 2.1.2 on 2018-11-18 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiorder', '0003_auto_20181114_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiorder.Store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('my_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiorder.MyCart')),
                ('purchasable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiorder.Purchasable')),
            ],
        ),
        migrations.CreateModel(
            name='MyCartItemOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('my_cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiorder.MyCartItem')),
                ('purchasable_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiorder.PurchasableOption')),
            ],
        ),
    ]
