# Generated by Django 2.1.3 on 2018-11-17 06:00

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kiorder', '0003_auto_20181110_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(null=True, upload_to='images/thumbnail/')),
            ],
        ),
        migrations.AddField(
            model_name='purchasable',
            name='badges',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='kiorder.Badge'),
        ),
    ]
