# Generated by Django 2.1.2 on 2018-11-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiorder', '0004_mycart_mycartitem_mycartitemoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycartitemoption',
            name='purchasable_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiorder.PurchasableOption'),
        ),
    ]
