# Generated by Django 2.1.2 on 2018-12-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiorder', '0004_auto_20181117_0600'),
        ('kiorder', '0005_auto_20181129_1253'),
    ]

    operations = [
    ]
