# Generated by Django 2.1.4 on 2018-12-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiorder', '0003_auto_20181111_0802'),
        ('kiorder', '0006_merge_20181203_0923'),
    ]

    operations = [
    ]
